### ISSUE TITLE
TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by damusix** [felixheck/laabr#43]
Issue when using laabr with hapipal/hecks because of `JSON.stringify(data.payload)`. I am trying to implement `bull-arena` or `bull-board` in hapi since I am using `bull` as a worker. When I attempt to retry a failing job, I get this circular structure error. This is completely crashing my worker.

```
➜  laabr-circ-ref node index.js
1571340150312 info server started at: http://iesous:3000
(node:36683) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.data [as payload] (/usr/app/issues/laabr-circ-ref/node_modules/laabr/src/tokens.js:124:8)
    at eval (eval at format.replace (/usr/app/issues/laabr-circ-ref/node_modules/laabr/src/logger.js:48:23), <anonymous>:1:72)
    at format.replace (/usr/app/issues/laabr-circ-ref/node_modules/laabr/src/logger.js:48:23)
    at String.replace (<anonymous>)
    at compile (/usr/app/issues/laabr-circ-ref/node_modules/laabr/src/logger.js:39:21)
    at /usr/app/issues/laabr-circ-ref/node_modules/laabr/src/logger.js:84:25
    at Object.write (/usr/app/issues/laabr-circ-ref/node_modules/pino/lib/tools.js:237:25)
    at Pino.write (/usr/app/issues/laabr-circ-ref/node_modules/pino/lib/proto.js:153:15)
    at Pino.LOG (/usr/app/issues/laabr-circ-ref/node_modules/pino/lib/tools.js:36:21)
(node:36683) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
(node:36683) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
1571340153978 GET 127.0.0.1 http://localhost:3000/queues/?test=failed 200 {} (17 ms)
1571340156102 GET 127.0.0.1 http://localhost:3000/queues/?test=failed 200 {} (7 ms)
```

Steps to reproduce:

```
mkdir laabrtest
cd laabrtest
npm i @hapi/hapi bull bull-board hecks laabr
touch index.js
```

Then, in index.js paste in this:

```js
const bull = require('bull');
const hapi = require('@hapi/hapi');
const laabr = require('laabr');
const hecks = require('hecks');
const express = require('express');
const { setQueues, UI } = require('bull-board');

const server = hapi.Server({ port: 3000 });

const queue = new bull('test');

// queue always throws error so we can retry
queue.process(() => {

    throw Error('there was an error');
});

const app = express();
app.use('/', UI);

(async () => {

    setQueues([queue]);

    await server.register([
        laabr,
        hecks
    ]);

    server.route({
        method: '*',
        path: '/{expressPath*}',
        handler: {
            express: app
        }
    });

    await server.start();

    queue.add({ thisthing: 'should break' });
})();
```

Start your server and go to `http://localhost:3000`
Go to your failed jobs and retry.
You should get the error I paste above.

**Comment by felixheck** [comment]
Hi and thanks for your great issue — simplified my work lots of 🙏 

As already mentioned in the Slack workspace, there's currently no way to handle properly all the payload formats which does not fit `route.options.payload.output = data`. 

So, I just published a patch `v5.1.5` which logs `[IncomingMessage]` or `[Readable]` in such cases.

Possible solution for you are:

1) be okay with the solution mentioned above
2) override the parsing options of your plugged in express app
3) ignore the express/UI paths in the `hapi-pino` options

In case of any further questions, feel free to reach directly out to me in Slack.
Cheers
